### PR TITLE
Replace linux dot org logo with Tux.

### PR DESCRIPTION
**Pull request by NotAProton**
Signed-off-by: NotAProton <notaproton8@gmail.com>

The change: 
Live: https://notaproton.github.io/tux-tenacity-webpage/
linux dor org logo

to 
Chubby tux

Why tux?

1) I did not see anything about the license of the linux dot org logo. Unless it is stated that is under the public domain we have to assume that the image is under copyright and we could get sued for using it on the website. This tux is under GPL v2 https://en.wikipedia.org/wiki/Tux_(mascot)#/media/File:TuxFlat.svg

2)<pre>f a t     p e n g u i n     g o o d   (•∋•)</pre>

### CODE REVIEW

**Comment by Sosasees** [comment]
Please host your fork on Github pages, as per the [Contributing Guidelines](https://web.archive.org/web/20210904152208/https://github.com/Sosasees/tenacity-webpage/blob/main/CONTRIBUTING.md).

**Comment by NotAProton** [comment]
sorry
https://notaproton.github.io/tux-tenacity-webpage/

**Comment by Sosasees** [comment]
This is a nasty crop because
there's not enough whitespace in the top of the circle,
making it look like Tux is barely touching a ceiling.



So I made my own crop of Tux.
It's much more recognizable at that small size because,
even though Tux's face is barely distinguishable at just 14 × 14 pixels,
the added whitespace makes theys overall silhouette much more clear.

[This](https://sosasees.github.io/tenacity-webpage) is the result.

**Comment by NotAProton** [comment]
yeah, that looks better

**Pull request closed without merging**
